// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnXtBG0JfUFDJzkuG5XukCJg9pP9gTLNA',
    appId: '1:495179430385:web:8f6e0a04d58f271a226c50',
    messagingSenderId: '495179430385',
    projectId: 'ashristore-c781d',
    authDomain: 'ashristore-c781d.firebaseapp.com',
    storageBucket: 'ashristore-c781d.firebasestorage.app',
    measurementId: 'G-KKRY6Y3K34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZvr3ynWIsumMT8MLebV99UFqnk1XEkeE',
    appId: '1:495179430385:android:e41da361f7a047e3226c50',
    messagingSenderId: '495179430385',
    projectId: 'ashristore-c781d',
    storageBucket: 'ashristore-c781d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZko3DS_j_Lo8FyNpanNpCdDmmyioFFqM',
    appId: '1:495179430385:ios:b98d8684829f4b75226c50',
    messagingSenderId: '495179430385',
    projectId: 'ashristore-c781d',
    storageBucket: 'ashristore-c781d.firebasestorage.app',
    iosBundleId: 'com.example.ashristore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZko3DS_j_Lo8FyNpanNpCdDmmyioFFqM',
    appId: '1:495179430385:ios:b98d8684829f4b75226c50',
    messagingSenderId: '495179430385',
    projectId: 'ashristore-c781d',
    storageBucket: 'ashristore-c781d.firebasestorage.app',
    iosBundleId: 'com.example.ashristore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnXtBG0JfUFDJzkuG5XukCJg9pP9gTLNA',
    appId: '1:495179430385:web:b4c8576e826fed1d226c50',
    messagingSenderId: '495179430385',
    projectId: 'ashristore-c781d',
    authDomain: 'ashristore-c781d.firebaseapp.com',
    storageBucket: 'ashristore-c781d.firebasestorage.app',
    measurementId: 'G-5BH23CQCKN',
  );
}
